In [1]:
import pandas as pd

In [3]:
data = pd.read_csv("/Users/rachelbozadjian/Desktop/load_data.csv")

data.columns

Index(['URL_OrigBrightfield_L', 'URL_OrigBrightfield_H', 'URL_OrigBrightfield',
       'URL_OrigRNA', 'URL_OrigMito', 'URL_OrigER', 'URL_OrigDNA',
       'URL_OrigAGP', 'Metadata_Source', 'Metadata_Batch', 'Metadata_Plate',
       'Metadata_Well', 'Metadata_Site', 'Metadata_AbsPositionZ',
       'Metadata_AbsTime', 'Metadata_BinningX', 'Metadata_BinningY',
       'Metadata_ChannelID', 'Metadata_ChannelName', 'Metadata_Col',
       'Metadata_ExposureTime', 'Metadata_FieldID',
       'Metadata_ImageResolutionX', 'Metadata_ImageResolutionY',
       'Metadata_ImageSizeX', 'Metadata_ImageSizeY',
       'Metadata_MainEmissionWavelength', 'Metadata_MainExcitationWavelength',
       'Metadata_MaxIntensity', 'Metadata_ObjectiveMagnification',
       'Metadata_ObjectiveNA', 'Metadata_PlaneID', 'Metadata_PositionX',
       'Metadata_PositionY', 'Metadata_PositionZ', 'Metadata_Row'],
      dtype='str')

In [4]:
filtered_data = data[["URL_OrigBrightfield_L", "URL_OrigBrightfield_H", "URL_OrigBrightfield", "URL_OrigRNA", "URL_OrigMito", "URL_OrigER", "URL_OrigDNA", "URL_OrigAGP", "Metadata_Source", "Metadata_Batch", "Metadata_Plate", "Metadata_Well", "Metadata_Site", "Metadata_Col", "Metadata_FieldID", "Metadata_PlaneID", "Metadata_Row"]]
filtered_data.head()

,URL_OrigBrightfield_L,URL_OrigBrightfield_H,URL_OrigBrightfield,URL_OrigRNA,URL_OrigMito,URL_OrigER,URL_OrigDNA,URL_OrigAGP,Metadata_Source,Metadata_Batch,Metadata_Plate,Metadata_Well,Metadata_Site,Metadata_Col,Metadata_FieldID,Metadata_PlaneID,Metadata_Row
0,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,A01,1,1,1,1,1
1,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,A01,2,1,2,1,1
2,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,A01,3,1,3,1,1
3,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,A01,4,1,4,1,1
4,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,A01,5,1,5,1,1

In [33]:
longer_data = pd.melt(
    filtered_data,
    id_vars=['Metadata_Source', 'Metadata_Batch', 'Metadata_Plate', 'Metadata_Well', 
             'Metadata_Site', 'Metadata_Col', 'Metadata_FieldID', 'Metadata_PlaneID', 'Metadata_Row'],
    value_vars=['URL_OrigBrightfield_L', 'URL_OrigBrightfield_H', 'URL_OrigBrightfield', 
                'URL_OrigRNA', 'URL_OrigMito', 'URL_OrigER', 'URL_OrigDNA', 'URL_OrigAGP'],
    var_name='channel',
    value_name='path'
)

# Clean up the URL_type column to remove the 'URL_Orig' prefix
longer_data['channel'] = longer_data['channel'].str.replace('URL_Orig', '')

longer_data = longer_data.rename(columns={"Metadata_Source":"source", "Metadata_Batch":"batch", "Metadata_Plate":"plate", "Metadata_Well":"well", "Metadata_Site":"site", "Metadata_Col":"col", "Metadata_FieldID":"field_id", "Metadata_PlaneID":"plane_id", "Metadata_Row":"row"})

df_reordered = longer_data[['channel', 'path', 'source', 'batch', 'plate', 'well', 'site', 'col', 'field_id',
       'plane_id', 'row']]

df_reordered

,channel,path,source,batch,plate,well,site,col,field_id,plane_id,row
0,Brightfield_L,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,A01,1,1,1,1,1
1,Brightfield_L,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,A01,2,1,2,1,1
2,Brightfield_L,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,A01,3,1,3,1,1
3,Brightfield_L,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,A01,4,1,4,1,1
4,Brightfield_L,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,A01,5,1,5,1,1
...,...,...,...,...,...,...,...,...,...,...,...
27643,AGP,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,P24,5,24,5,1,16
27644,AGP,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,P24,6,24,6,1,16
27645,AGP,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,P24,7,24,7,1,16
27646,AGP,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,P24,8,24,8,1,16
27647,AGP,s3://cellpainting-gallery/cpg0016-jump/source_...,source_4,2021_04_26_Batch1,BR00117035,P24,9,24,9,1,16

In [35]:
pd.DataFrame.to_csv(df_reordered, "samplesheet_test_full.csv", index=False)